##Server Settings
server:
  port: 8080
#  port: ${PORT}

spring:
  #  datasource:
  #    url: ${DATABASE_URL}
  #    username: sa
  #    password:
  #    driver-class-name: ${DRIVER_CLASS_NAME}
  ## Swagger3.0-ui Settings
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace